# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/eduai
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

# AI Keys (Move these to environment variables in production)
spring.ai.openai.api-key=${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}