# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/eduai
spring.datasource.username=[prashantprakash]
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Configuration
spring.main.allow-bean-definition-overriding=true